Display value of assets converted to base currency
DimoDimchev/Trivial pull request #205
Opened 2021-11-08 19:11 UTC by Sheko1

Example for balance assets:
```json
                "1100c805-ed03-4e83-9131-003726d1f0e4": {
                    "balanceData": {
                        "amount": "7588.97",
                        "base_currency": 10217.7937610489,
                        "currency": "GBP"
                    },
                    "providerName": "Wise"
                },
                "582a6ea9-81c7-4def-952d-85709d9432cf": {
                    "balanceData": {
                        "amount": "2021.12",
                        "base_currency": 2336.484683697369,
                        "currency": "EUR"
                    },
                    "providerName": "Sandbox Finance"
                }
```
base currency here is **USD**

Example for holdings:

```json
                "285049704391582044458143247520922312132": {
                    "base_currency": 0.5517360817076,
                    "quantity": "0.26117128",
                    "symbol": "ADA"
                },
                "315994969760573053020021447413241409761": {
                    "base_currency": 34.536392683946815,
                    "quantity": "0.00052389",
                    "symbol": "BTC"
                }
```

base currency here is **USD**

Closes #204

2021-11-08 23:02 UTC, KoliosterNikolayIliev approved these changes

2021-11-09 08:15 UTC, DimoDimchev requested changes

2021-11-09 08:15 UTC, DimoDimchev commented on server/portfolio/portfolio/blueprints/api.py
> +
Please look at the logic changes that have been made in Portfolio in #206 . I think it should look something like this
```suggestion
        balances = convert_assets_value_to_base_currency(user_data['base_currency'], responses[0])
        holdings = convert_assets_value_to_base_currency(user_data['base_currency'], responses[1])
```

2021-11-09 08:48 UTC, Sheko1 commented on server/portfolio/portfolio/blueprints/api.py
> +
done in commit 6d4a61d01110eec44b145a70bc7b1577a0e4c996

2021-11-09 09:23 UTC, DimoDimchev approved these changes

2021-11-09 12:18 UTC, merged